version: "3.8"

services:
  api_server:
    container_name: app_server
    build:
      context: ./server
      dockerfile: dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
      - $HOME/uploads:/app/uploads
    depends_on:
      - mongodb_cbt
    restart: always
    ports:
      - 9000:9000
    environment:
      DB_HOST: mongodb_cbt ## same as the database service name
      DB_PORT: 27017
      DB_USER: jamiebones
      DB_DATABASE: CBT_Database
      DB_PASSWORD: blazing147
      NODE_ENV: test

  mongodb_cbt:
    hostname: mongodb_cbt
    container_name: mongodb_cbt
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: jamiebones
      MONGO_INITDB_ROOT_PASSWORD: blazing147
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--journal",
        "--dbpath",
        "/data/db",
        "--enableMajorityReadConcern",
        "false",
      ]
    volumes:
      - $HOME/cbt_data/mongodb_cbt:/data/db # This is where your volume will persist. e.g. VOLUME-DIR = ./volumes/mongodb
      - $HOME/cbt_data/mongodb_cbt_configdb:/data/configdb